#!/bin/bash
# Phase 1: DCU/ROCm 运行时环境（低风险提分优先）
export HIP_PLATFORM="${HIP_PLATFORM:-amd}"
export HIP_VISIBLE_DEVICES="${HIP_VISIBLE_DEVICES:-0}"
export GPU_MAX_HW_QUEUES="${GPU_MAX_HW_QUEUES:-2}"
export HSA_ENABLE_SDMA="${HSA_ENABLE_SDMA:-1}"
export PYTORCH_HIP_ALLOC_CONF="${PYTORCH_HIP_ALLOC_CONF:-expandable_segments:True}"
export HIP_FORCE_DEV_KERNARG="${HIP_FORCE_DEV_KERNARG:-1}"

export FDU_ENABLE="${FDU_ENABLE:-1}"
export FDU_KV_CACHE_STRATEGY="${FDU_KV_CACHE_STRATEGY:-defrag}"
export FDU_ATTENTION_BACKEND="${FDU_ATTENTION_BACKEND:-dcu_optimized}"
# 默认关：精度风险最高；SCNet 验证 Δ≤1% 后再开
export FDU_ENABLE_KV_QUANT="${FDU_ENABLE_KV_QUANT:-0}"
export FDU_ENABLE_PREFIX_CACHE="${FDU_ENABLE_PREFIX_CACHE:-1}"
export FDU_ENABLE_HIP_GRAPH="${FDU_ENABLE_HIP_GRAPH:-0}"
export FDU_ENABLE_GQA_OPT="${FDU_ENABLE_GQA_OPT:-1}"
