#!/usr/bin/env bash

export HIP_VISIBLE_DEVICES="${HIP_VISIBLE_DEVICES:-0}"
export PYTORCH_HIP_ALLOC_CONF="${PYTORCH_HIP_ALLOC_CONF:-expandable_segments:True}"
export SAFETENSORS_FAST_GPU="${SAFETENSORS_FAST_GPU:-1}"
export VLLM_ROCM_USE_AITER="${VLLM_ROCM_USE_AITER:-0}"
export VLLM_ROCM_USE_SKINNY_GEMM="${VLLM_ROCM_USE_SKINNY_GEMM:-1}"
export FDU_FORCE_STOCK_GEMM="${FDU_FORCE_STOCK_GEMM:-0}"
export FDU_ENABLE="${FDU_ENABLE:-0}"
export FDU_GFX936_QUANT_MODE="${FDU_GFX936_QUANT_MODE:-off}"

unset HSA_OVERRIDE_GFX_VERSION ROCBLAS_LAYER

export FDU_CACHE_ROOT="${FDU_CACHE_ROOT:-/public/home/xdzs2026_c415/cache}"
export VLLM_CACHE_ROOT="${VLLM_CACHE_ROOT:-$FDU_CACHE_ROOT/vllm}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-$FDU_CACHE_ROOT/triton}"
export MIOPEN_USER_DB_PATH="${MIOPEN_USER_DB_PATH:-$FDU_CACHE_ROOT/miopen}"
export MIOPEN_CUSTOM_CACHE_DIR="${MIOPEN_CUSTOM_CACHE_DIR:-$FDU_CACHE_ROOT/miopen}"

mkdir -p \
    "$VLLM_CACHE_ROOT" \
    "$TRITON_CACHE_DIR" \
    "$MIOPEN_USER_DB_PATH" \
    "$MIOPEN_CUSTOM_CACHE_DIR"
